apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-tanzu-env
spec:
  title: Spring Cloud Gateway on Kubernetes
  description: An interactive workshop on Spring Cloud Gateway on K8s
  url: https://github.com/samarsinghal/lab-tanzu-env
  content:
    image: docker.io/samarsinghal/tanzu_env:latest
    files: github.com/samarsinghal/lab-tanzu-env
  vendor: eduk8s.io
  difficulty: intermediate
  duration: 120m
  tags:
  - containers
  session:
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      docker:
        enabled: true
      registry:
        enabled: true
